/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ismael' at '13/06/16 21:56' with Gradle 2.11
 *
 * @author ismael, @date 13/06/16 21:56
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
